module.exports =[

    {
        id: 1,
        beerType: "IPA",
        beerName: "The Inner Eye",
        description: "Dry hopped with Citra, Simcoe and Cascade, The Inner Eye is a full flavoured, easy drinking pale ale. It boasts a large bouquet of tropical fruit and citrus while keeping bitterness low to improve drinkability. The palate is soft and full, finishing medium dry to accentuate it's juicy qualities.",
        rating: 4,
        season: "fall",
        ABV: "5.5%",
        flavor: "Citrus",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498891/Used/pexels-vin%C3%ADcius-caricatte-4243302_noireq.jpg",
        brewery_id: 2
    },
    {
        id: 2,
        beerType: "IPA",
        beerName: "Life in the Clouds",
        description: "Simcoe and Mosaic hops balance each other to make this juicy IPA explosively fruit forward in both taste and aroma while curbing any unbearable sweetness to make an extremely drinkable beer.",
        rating: 4.5,
        season: "not specified",
        ABV: "6.1%",
        flavor: "Citrus",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498882/Used/pexels-dorte-237774_lrh2ge.jpg",
        brewery_id: 1
    },
    {
        id: 3,
        beerType: "IPA",
        beerName: "High Grade",
        description: "IPA brewed with barley, oats & a fat bag of Simcoe, Idaho 7, Citra & Mosaic.",
        rating: 4,
        season: "fall",
        ABV: "5.8%",
        flavor: "Mango, Pineapple, Peach",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498880/Used/pexels-elevate-1267682_fwgngx.jpg",
        brewery_id: 4
    },
    {
        id: 4,
        beerType: "IPA",
        beerName: "The Universe",
        description: "Galaxy hops from Myrtleford, Victoria in Australia and Mosaic hops from Yakima, Washington, USA, deliver aromas and flavours of tropical fruits, mango and citrus. Light malt body lets the hops shine through, and finishes crisp but not bitter.",
        rating: 3.5,
        season: "spring",
        ABV: "4.8%",
        flavor: "Citrus, Caramel",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638497224/Used/beer_4_csboul.jpg",
        brewery_id: 12
    },
    {
        id: 5,
        beerType: "Amber Ale",
        beerName: "Full Sail",
        description: "Vaguely orange and woodsy nose with a campfire-like note. The sip is thin but sweet, with a sharp caramel-citrus note that lingers. Only mild bitterness. Accessibility at the expense of interest.",
        rating: 4,
        season: "fall",
        ABV: "6.1%",
        flavor: "Mango, Citrus",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638497225/Used/beer_1_fffnlh.jpg",
        brewery_id: 13
    },
    {
        id: 6,
        beerType: "Amber Ale",
        beerName: "Ridgetop Red",
        description: "Softly engaging nose of berry, melon, and banana, with a faint earthy and bready back note. The sip steers almost woody, with a mid-range bitterness for structure. Classically cohesive.",
        rating: 3.5,
        season: "fall",
        ABV: "5.1%",
        flavor: "Berry, Melon, Banana",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498890/Used/pexels-evgeniy-alekseyev-7418939_mon8hi.jpg",
        brewery_id: 11
    },
    {
        id: 7,
        beerType: "Amber Ale",
        beerName: "Hop Butcher",
        description: "Candied tropical fruit nose: pineapple, lychee, apricot, peach. The sip joins light tannic malt bite with very gentle hops bitterness, lingering caramel malt, and less-overt fruit. Compelling blend of cutting-edge hopping with classic craft style.",
        rating: 3,
        season: "fall",
        ABV: "5.6%",
        flavor: "Pineapple, Apricot, Lychee",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498896/Used/kanan-khasmammadov-8pUytjGU-E0-unsplash_oh0ul2.jpg",
        brewery_id: 9
    },
    {
        id: 8,
        beerType: "Amber Ale",
        beerName: "Blood of Gods",
        description: "Very subtle nose—wood shavings, light citrus. The sip pushes hefty caramel-malt sweetness, accented by citrus notes, backed by mild bitterness that pulls into focus in the finish. Between the woody notes and slightly ragged bitterness, it may not satisfy drinkers of smoother red ales.",
        rating: 4,
        season: "fall",
        ABV: "6.6%",
        flavor: "Citrus, Caramel",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498890/Used/pexels-rodnae-productions-5737367_bjju4o.jpg",
        brewery_id: 7
    },
    {
        id: 9,
        beerType: "Lager",
        beerName: "Trans Human State",
        description: "This rendition is striking with a bright yellow straw hue. We've amplified the bitterness to balance perfectly with a soft mouthfeel and bready malt backbone. We dry hopped with Hallertau Blanc and Huell Melon to provide aromas and flavours of fresh lemon, honey and a touch of melon.",
        rating: 4.5,
        season: "summer",
        ABV: "5.0%",
        flavor: "Lemon, Melon, Honey",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498880/Used/pexels-cottonbro-5530264_qbz8br.jpg",
        brewery_id: 2
    },
    {
        id: 10,
        beerType: "Lager",
        beerName: "Audio/Visual Lager",
        description: "We use Wai-iti hops for fresh notes of lime and mandarin citrus to round out this easy drinking lager. It's the ideal beer for concerts, green rooms, backyards or wherever you tune in!",
        rating: 3,
        season: "not specified",
        ABV: "5.2%",
        flavor: "Citrus, Mandarin",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498880/Used/pexels-jess-low-2574851_ijnq75.jpg",
        brewery_id: 1
    },
    {
        id: 11,
        beerType: "Lager",
        beerName: "Shindig",
        description: "Shindig is a good 'ol time, Pivo-style Pilsner brewed with 100% Canadian Barley Malt and German hops. Its medium-light body has elegant cereal and baked bread character, with low bitterness and a refined and refreshing finish.",
        rating: 4.5,
        season: "summer",
        ABV: "4.2%",
        flavor: "Baked Bread",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498892/Used/bence-boros-8T5UAV6KkZA-unsplash_s4jcoy.jpg",
        brewery_id: 3
    },
    {
        id: 12,
        beerType: "Lager",
        beerName: "Smooth Sailing",
        description: "Smooth Sailing is a well crafted light lager that is brewed with premium Canadian malts and treated water straight from Indie Brewing's aquifer for a thirst quenching and refreshingly good time. It's all smooth sailing from here on out.",
        rating: 4,
        season: "summer",
        ABV: "4.0%",
        flavor: "Citrus, Biscuit",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498893/Used/jon-parry-C8eSYwQkwHw-unsplash_pxlx1r.jpg",
        brewery_id: 5
    },
    {
        id: 13,
        beerType: "Porter",
        beerName: "Double Trouble Pecan Porter",
        description: "A robust porter that's enhanced with natural pecan flavour. It's dark, complex and flavourful with malty, roasted, chocolate and nutty aromas leading to flavours of coffee, burnt sugar and chocolate milk.",
        rating: 4.5,
        season: "winter",
        ABV: "5.9%",
        flavor: "Coffee, Burned Sugar, Chocolate",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498894/Used/josh-olalde-YjTtHDe-5Z0-unsplash_sjquib.jpg",
        brewery_id: 6
    },
    {
        id: 14,
        beerType: "Porter",
        beerName: "Stranger Than Fiction",
        description: "This porter shows an opaque brown/black colour with thick, long-lasting head. Complex aromas of molasses, coffee, smoke, toasted nuts and chocolate.",
        rating: 5,
        season: "winter",
        ABV: "6.3%",
        flavor: "Coffee, Nuts, Chocolate",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498894/Used/devon-hawkins-8dhhg9QIpw0-unsplash_naq5hq.jpg",
        brewery_id: 3
    },
    {
        id: 15,
       beerType: "Porter",
        beerName: "Pitchfork Brewers",
        description: "A wonderful take on an English-style porter. It pours dark brown with delightful aromas and flavours of coffee, dark chocolate, cocoa, and toasted nuts. Full-bodied and roasted with a long, flavourful finish.",
        rating: 3.5,
        season: "winter",
        ABV: "4.5%",
        flavor: "Coffee, Nuts, Chocolate",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498891/Used/pexels-erik-mclean-4850282_yw4ytz.jpg",
        brewery_id: 4 
    },
    {
        id: 16,
        beerType: "Stout",
        beerName: "Choclate Manifesto",
        description: "Need we say more? This triple-chocolate milk stout is a wonderful gift for the chocolate lover who doesn't mind sharing. Maybe they'll choose to share with you.",
        rating: 3,
        season: "winter",
        ABV: "5.8%",
        flavor: "Chocolate",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498881/Used/pexels-caio-59150_yighnu.jpg",
        brewery_id: 8
    },
    {
        id: 17,
        beerType: "Stout",
        beerName: "Dragon Stout",
        description: "Dark brown/black colour; distinctive, smoky, malty nose; rich, bitter/sweet flavours with smoky and leathery notes.",
        rating: 4,
        season: "winter",
        ABV: "6.4%",
        flavor: "Malty, Smoky",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498880/Used/pexels-tim-durben-1025113_1_drh1lr.jpg",
        brewery_id: 11
    },
    {
        id: 18,
        beerType: "Stout",
        beerName: "Cobblestone Nitro Strout",
        description: "Deep, almost black colour; forward aromas of chocolate, roasted coffee and malt; creamy texture with a long finish.",
        rating: 4,
        season: "winter",
        ABV: "6.2%",
        flavor: "Chocolate, Coffee",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498878/Used/pexels-helena-lopes-1796698_nlpfde.jpg",
        brewery_id: 12
    },
    {
        id: 19,
        beerType: "Stout",
        beerName: "Midnight Kissed My Cow",
        description: "The palate is medium bodied with soft carbonation and light bitterness balancing the robust chocolate flavours.",
        rating: 4.5,
        season: "winter",
        ABV: "5.2%",
        flavor: "Chocolate",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498878/Used/pexels-elevate-1267363_nznryd.jpg",
        brewery_id: 16
    },
    {
        id: 20,
        beerType: "Pale Ale",
        beerName: "Spitfire",
        description: "Clear deep amber with a dense cream head; on the nose are notes of toffee, grapefruit, honey, crusty fresh bread, dried flower and grassy hops; on the palate it is medium bodied and moderately carbonated, with flavours of bready malt, caramel and bitter hop presence that lingers on the finish.",
        rating: 5,
        season: "not specified",
        ABV: "4.2%",
        flavor: "Grapefruit, Honey, Caramel",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498879/Used/pexels-anete-lusina-5238428_f2dgad.jpg",
        brewery_id: 16
    },
    {
        id: 21,
        beerType: "Pale Ale",
        beerName: "Iron Maiden Trooper",
        description: "This Trooper Ale is handcrafted by Robinsons, one of the oldest and most respected names in British brewing history. Look for deep golden colour with rich malt and citrus notes from a unique blend of hops that add balance.",
        rating: 3.5,
        season: "not specified",
        ABV: "5.9%",
        flavor: "Citrus, Hops",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498883/Used/pexels-streetwindy-2606028_kipnpy.jpg",
        brewery_id: 5
    },
    {
        id: 22,
        beerType: "Pale Ale",
        beerName: "Sierra Nevada",
        description: "Pours an amber gold, with a moderate head; aromas of sweet roasted malt, biscuit, and citrus, with notes of pine and spice; dryish and medium-bodied with a creamy palate, and flavours of toasted malt, caramel, grapefruit and tropical fruit; a crisp, lingering, pleasantly balanced bitterness on the finish.",
        rating: 4.5,
        season: "not specified",
        ABV: "6.9%",
        flavor: "Grapefruit, Caramel",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498883/Used/pexels-rodnae-productions-8342012_nehpso.jpg",
        brewery_id: 7
    },
    {
        id: 23,
        beerType: "Pale Ale",
        beerName: "Sierra Nevada",
        description: "Amber colour with long-lasting head; floral, oatmeal, malt and hops aromas; medium-bodied, creamy taste with clean bitter finish.",
        rating: 5,
        season: "not specified",
        ABV: "5.4%",
        flavor: "Oatmeal",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498886/Used/pexels-los-muertos-crew-8477416_g2cnz7.jpg",
        brewery_id: 6
    },
    {
        id: 24,
        beerType: "Sour",
        beerName: "Bellwoods Jelly King",
        description: "This dry-hopped, sour ale combines the best of both aromatic hops and tangy acidity with spectacular results. Naturally hazy gold with aromas and flavours of tropical fruit, tangerine, peach and cedar, leading to notes of earth and yeast.",
        rating: 5,
        season: "summer",
        ABV: "6.4%",
        flavor: "Tangerine, Peach, Cedar",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498888/Used/pexels-cup-of-couple-7660472_suqzps.jpg",
        brewery_id: 6
    },
    {
        id: 25,
        beerType: "Sour",
        beerName: "Jam Up The Mash",
        description: "This brew uses multiple fermentations to attain a refreshing sour and hoppy mix. Aromas and flavours of lemon, kiwi, guava, spice and green mango with pine, leaf/herb, earth and lactic notes. Palate is dry and refreshingly tart on the finish.",
        rating: 4,
        season: "summer",
        ABV: "4.4%",
        flavor: "Lemon, Guava, Mango",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498896/Used/louis-hansel-dfMWjLCXoSc-unsplash_lnrtmw.jpg",
        brewery_id: 10
    },
    {
        id: 26,
        beerType: "Sour",
        beerName: "Passionate",
        description: "This sour is pale gold with a light haze, showcasing tangy passionfruit, toasted coconut, tropical stone fruit, bread crust notes. The addition of lactose provides a creamy finish.",
        rating: 4.5,
        season: "summer",
        ABV: "5.6%",
        flavor: "Coconut, Passionfruit",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498894/Used/jon-parry-Qk5c2bEnzEM-unsplash_bsqpeh.jpg",
        brewery_id: 11
    },
    {
        id: 27,
        beerType: "Sour",
        beerName: "Blood Moon Orange",
        description: "Pouring hazy amber. Dominant aromas of blood orange, along with grapefruit, orange peel. Light and tart with a crisp, lengthy finish.",
        rating: 4.5,
        season: "summer",
        ABV: "5.8%",
        flavor: "Orange, Grapefruit",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498889/Used/pexels-karolina-grabowska-4968337_gbgpxe.jpg",
        brewery_id: 12
    },
    {
        id: 28,
        beerType: "Sour",
        beerName: "Ebb & Flow",
        description: "This sour explodes with aromas and flavours of ripe plum and juicy boysenberry, along with malt and citrusy, floral hops. It's light-bodied and fruity with a long, tangy finish.",
        rating: 3.5,
        season: "summer",
        ABV: "4.8%",
        flavor: "Plum, Boysenberry",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498892/Used/pexels-gustavo-santana-5860684_g5xsqf.jpg",
        brewery_id: 9
    },
    {
        id: 29,
        beerType: "Sour",
        beerName: "Staring Down The Sun",
        description: "This sour and fruity offering bursts with flavours of juicy clementine, a touch of malt and the tart acidity of a sour ale.",
        rating: 3,
        season: "summer",
        ABV: "4.3%",
        flavor: "Clementine",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498886/Used/pexels-rachel-claire-5531045_laxtrc.jpg",
        brewery_id: 15
    },
    {
        id: 30,
        beerType: "IPA",
        beerName: "Juicy Ass",
        description: "Their award-winning IPA is hazy gold in colour, with intense citrus, piney and pineapple aromas. On the palate, an explosion of grapefruit and tropical fruit flavours, followed by a cleansing, bitter finish.",
        rating: 4,
        season: "not specified",
        ABV: "6.5%",
        flavor: "Pineapple, Citrus",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498880/Used/pexels-cottonbro-5530264_qbz8br.jpg",
        brewery_id: 5

    },
    {
        id: 31,
        beerType: "IPA",
        beerName: "Amsterdam Boneshaker",
        description: "Pours a hazy amber with aromas of grapefruit, orange peel, pineapple and resinous hops. The palate is full, rich and well carbonated, with flavours that deliver what the nose promised. Long and fruity, bitter hop finish.",
        rating: 3.5,
        season: "not specified",
        ABV: "5.7%",
        flavor: "Pineapple, Grapefruit, Orange",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498879/Used/pexels-anete-lusina-5238428_f2dgad.jpg",
        brewery_id: 7

    },
    {
        id: 32,
        beerType: "Amber Ale",
        beerName: "Broadhead",
        description: "Clear copper colour; aromas of coffee bean and toasted nuts with floral and apple notes; medium in body, with balanced bitterness and a refreshing carbonation; nutty flavours, with subtle notes of apple, apricot and spice; moderate bitterness emerges and carries through to a crisp finish.",
        rating: 4,
        season: "fall",
        ABV: "6.4%",
        flavor: "Mango, Citrus",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498884/Used/pexels-engin-akyurt-3356408_nmhbln.jpg",
        brewery_id: 8

    },
    {
        id: 33,
        beerType: "Amber Ale",
        beerName: "Whiskeyjack Amber",
        description: "Expect aromas and flavours of caramel, toffee, roasted malt and bold hops. The palate is rich, smooth and balanced with a pleasantly hoppy finish.",
        rating: 4.5,
        season: "fall",
        ABV: "4.4%",
        flavor: "Caramel, Toffee",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498891/Used/pexels-jesus-arias-4623722_sf7pvg.jpg",
        brewery_id: 14

    },
    {
        id: 34,
        beerType: "Lager",
        beerName: "Sunset Point",
        description: "Light Melon gold, this unfiltered Barvarian style lager is crisp, clean and refreshing. It's perfect dockside or deckside.",
        rating: 3,
        season: "not specified",
        ABV: "5.0%",
        flavor: "Melon",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498892/Used/pexels-daniel-reche-6570569_xbgird.jpg",
        brewery_id: 16

    },
    {
        id: 35,
        beerType: "Lager",
        beerName: "Bear Naked Lager",
        description: "Straw gold in colour with notes of sweet malt, light hops, lemon, honey and almond notes. Light-bodied with a refreshingly crisp finish.",
        rating: 4.5,
        season: "not specified",
        ABV: "7.2%",
        flavor: "Melon, Honey, Nuts",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498893/Used/josh-olalde-b0EBo7iwLTQ-unsplash_xkiipt.jpg",
        brewery_id: 14

    },
    {
        id: 36,
        beerType: "Porter",
        beerName: "Salted Caramel Porter",
        description: "Creamy caramel and a savoury sprinkling of sea salt come together to make this deep brown ale the perfect finish to any hearty holiday feast. Handcrafted with roasted malts for a smooth, balanced brew, this Salted Caramel Porter has just a hint of sweetness.",
        rating: 5,
        season: "winter",
        ABV: "6.1%",
        flavor: "Caramel, Sea Salt",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498891/Used/pexels-erik-mclean-4850282_yw4ytz.jpg",
        brewery_id: 13

    },
    {
        id: 37,
        beerType: "Porter",
        beerName: "Back Roads",
        description: "Featuring flavours of coffee and chocolate, their porter is dark and luscious.",
        rating: 3.5,
        season: "winter",
        ABV: "6.1%",
        flavor: "Coffee, Chocolate",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498888/Used/pexels-roman-odintsov-5320333_ijh9rm.jpg",
        brewery_id: 10

    },
    {
        id: 38,
        beerType: "Stout",
        beerName: "Beyond the Pale Dark",
        description: "This rich and roasty Imperial Mexican Cake Stout pours dark brown. Anticipate aromas and flavours of cocoa, cinnamon, vanilla, and Scotch Bonnet peppers. It's full-bodied and spicy with a long, smooth, and slightly sweet finish.",
        rating: 4,
        season: "winter",
        ABV: "4.8%",
        flavor: "Chocolate, Cinnamon, Vanilla, Peppers",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498883/Used/pexels-elevate-1267356_vaeokf.jpg",
        brewery_id: 3
    },
    {
        id: 39,
        beerType: "Stout",
        beerName: "Winey Imperial Stout",
        description: "Aging in pinot noir barrels gives this stout its winey nature and cheeky name. Look for earthy aromas with pronounced grapey character on the nose; the palate is full and intense with flavours of molasses, cocoa, and figs.",
        rating: 5,
        season: "winter",
        ABV: "6.0%",
        flavor: "Grapes, Cocoa, Molasses, Figs",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638502878/pexels-cottonbro-5530252_of8khb.jpg",
        brewery_id: 7
    },
    {
        id: 40,
        beerType: "Pale Ale",
        beerName: "Beyond The Pale Aromatherapy",
        description: "This dry-hopped IPA is showing aromas and flavours of red grapefruit, grass, green tea and clove. Further notes of lychee, lemon and pineapple lead to a medium-bodied and dry palate with a mouth-watering finish;",
        rating: 3.5,
        season: "spring",
        ABV: "5.5%",
        flavor: "Grapefruit, Lemon, Pineapple",
        image: "../public/beer_1.jpg",
        brewery_id: 11
    },
    {
        id: 41,
        beerType: "Pale Ale",
        beerName: "Off the Grid",
        description: "Hazy in appearance with aromas of tropical fruit and tangerine, followed by flavours of mango, peach and grapefruit with earth and coconut. Smooth and creamy with a pleasant bitterness and fruity, floral tones on the dry finish.",
        rating: 4,
        season: "spring",
        ABV: "5.8%",
        flavor: "Grapefruit, Tangering, Peach",
        image: "../public/beer_1.jpg",
        brewery_id: 15
    },
    {
        id: 42,
        beerType: "Pale Ale",
        beerName: "Refined Fool",
        description: "This offering is pale gold in colour, with lively aromas and flavours of citrus, hops, passion fruit and pineapple. Full-bodied and fruity, with a refreshingly crisp finish.",
        rating: 4.5,
        season: "spring",
        ABV: "4.3%",
        flavor: "Citrus, Passionfruit, Pineapple",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498892/Used/pexels-daniel-reche-6570266_ep4rtf.jpg",
        brewery_id: 6
    },
    {
        id: 43,
        beerType: "Sour",
        beerName: "Sherbet Sour",
        description: "This sour is packed with key lime, pineapple, orange, and raspberry notes, which will remind you of a tropical island getaway. The medium-bodied and fruity palate leads you to a long finish.",
        rating: 4,
        season: "summer",
        ABV: "5.1%",
        flavor: "Lime, Pineapple, Orange, Raspberry",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498896/Used/louis-hansel-dfMWjLCXoSc-unsplash_lnrtmw.jpg",
        brewery_id: 16
    },
    {
        id: 44,
        beerType: "Sour",
        beerName: "Zap!",
        description: "This is a hand crafted sour IPA that's brimming with citrus and pink guava notes.",
        rating: 4,
        season: "summer",
        ABV: "4.1%",
        flavor: "Citrus, Guava",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638502878/pexels-alexandr-podvalny-1009068_ixkamr.jpg",
        brewery_id: 8
    },
    {
        id: 45,
        beerType: "IPA",
        beerName: "Disco Demolition Night",
        description: "This popular Tropical IPA has notes of mango, apricot and citrus wrapped up in a balanced and juicy palate.",
        rating: 5,
        season: "spring",
        ABV: "5.2%",
        flavor: "Citrus, Mango, Apricot",
        image: "https://res.cloudinary.com/dybcfr6cd/image/upload/v1638498884/Used/pexels-cottonbro-5537953_n0v7lu.jpg",
        brewery_id: 14
    }
];